angular.module('onlinebooksshop').constant("CONSTANT", {
	"URL" : "http://localhost:8080/webbookonline",
	"GETBOOKS" : "/GetBooks",
	"GET" : "GET",
	"POST" : "POST",
	"DELETEBOOK" : "/DeletBook",
	"succes" : 'success',
	"error" : "error",
	"AddBook" : "/AddBooks",
	"ExportBook" : "/ExportBook",
	"GETCUSTOMER" : "/GetCustomer",
	"DELETECUSTOMER" : "/DeleteCustomer",
	"ADDNEWCUSTOMER" : "/AddNewCustomer",
	"EXPORTCUSTOMER" : "/ExportCustomer",
	"GETORDERS" : "/GetOrders",
	"DELETEORDERS" : "/DeleteOrder",
	"ADDNEWORDERS" : "/AddNewOrder",
	"ORDERSBYCUSTOMERS" : "/OrderByIdCustomer",
	"EXPORTORDERS" : "/ExportOrder",
	"GETWRITER" : "/GetWriter",
	"DELETEWRITER" : "/DeletWriter",
	"ADDNEWWRITER" : "/AddNewWriter",
	"EXPORTWRITER" : "/ExportWriter",
	"EXPORTCSVBOOK" : "ExportBook.csv",
	"EXPORTCSVCUSTOMER" : "ExportCustomer.csv",
	"EXPORTCSVWRITER" : "ExportWriter.csv",
	"EXPORTCSVORDERS" : "ExportOrders.csv"

})