SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `id_book` INT(11) NOT NULL AUTO_INCREMENT,
  `name_Book` VARCHAR(45) NULL DEFAULT NULL,
  `writer_Book` VARCHAR(45) NULL DEFAULT NULL,
  `quantity_pages` INT(11) NULL DEFAULT NULL,
  `price` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_book`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `id_customer` INT(11) NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_customer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `id_order` INT(11) NOT NULL AUTO_INCREMENT,
  `id_book` INT(11) NOT NULL,
  `id_customer` INT(11) NOT NULL,
  `date_order` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_order`, `id_book`, `id_customer`),
  INDEX `fk_Order_Book_idx` (`id_book` ASC),
  INDEX `fk_Order_Customer1_idx` (`id_customer` ASC),
  CONSTRAINT `fk_Order_Book`
    FOREIGN KEY (`id_book`)
    REFERENCES `mydb`.`Book` (`id_book`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`id_customer`)
    REFERENCES `mydb`.`Customer` (`id_customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

DROP TABLE IF EXISTS `mydb`.`product` ;

DROP TABLE IF EXISTS `mydb`.`printer` ;

DROP TABLE IF EXISTS `mydb`.`pc` ;

DROP TABLE IF EXISTS `mydb`.`laptop` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;